FROM almalinux:9

RUN dnf -y install epel-release && \
    dnf -y install salt-minion && \
    dnf clean all

CMD ["bash", "-lc", "printf 'master: %s\n' \"${SALT_MASTER_HOST:-master}\" > /etc/salt/minion.d/master.conf && salt-minion -l info"]

